server.port: 2808

spring:
  application.name: gateway

eureka:
  instance.preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl.defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}